name: CapsLimit
version: 1.1.1
api: 3.0.0
main: CapsLimit\CapsLimit
authors: [deot]
# Twitter: @deotern
# Made by deot with <3

commands:
  capslimit:
    description: Sets maximum caps can be used by player
    permission: capslimit.set

permissions:
  capslimit.set:
    description: Allow to use set default usage of maximum caps!
    default: op
  capslimit.exception:
    description: Exception to get taken action if exceeded caps limit
    default: op
